### ISSUE TITLE
Fix ApplicationPane css usability

### ISSUE THREAD

**Issue by ptran099** [zmansiv/mercury-irc#3]
master/client/src/res/css/ApplicationPane.css

#left-topic-box {
	-fx-padding: 15px 15px 15px 15px;
}

should be

#left-topic-box {
	-fx-padding: 20px 15px 20px 15px;
}

**Comment by mlaux** [comment]
What does this fix? I made the change and was unable to tell any difference. 

That said, I just cloned and ran the client for the first time in years, and the design was all screwed up, which makes me think the CSS was not written in a forwards-compatible way and will likely require a major rewrite.
